export default{
  "login": "vilay1702",
  "id": 71513950,
  "node_id": "MDQ6VXNlcjcxNTEzOTUw",
  "avatar_url": "https://avatars.githubusercontent.com/u/71513950?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/vilay1702",
  "html_url": "https://github.com/vilay1702",
  "followers_url": "https://api.github.com/users/vilay1702/followers",
  "following_url": "https://api.github.com/users/vilay1702/following{/other_user}",
  "gists_url": "https://api.github.com/users/vilay1702/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/vilay1702/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/vilay1702/subscriptions",
  "organizations_url": "https://api.github.com/users/vilay1702/orgs",
  "repos_url": "https://api.github.com/users/vilay1702/repos",
  "events_url": "https://api.github.com/users/vilay1702/events{/privacy}",
  "received_events_url": "https://api.github.com/users/vilay1702/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Vilay Bende",
  "company": null,
  "blog": "",
  "location": "Indore, Madhya Pradesh, India",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 13,
  "public_gists": 0,
  "followers": 9,
  "following": 7,
  "created_at": "2020-09-18T14:38:50Z",
  "updated_at": "2021-07-28T18:52:43Z"
}